[project]
name = "weather-forcasting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "plotly>=6.0.1",
    "streamlit>=1.44.1",
]
